[package]
name = "proc"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.92"

[lib]
proc-macro = true
path = "./proc.rs"
